### ISSUE TITLE
[azure] Overwrite a blob should not preemptively delete (in case upload fails)

### ISSUE THREAD

**Issue by hponde** [christopher-hesse/blobfile#109]
If one is using the same path over and over for snapshot/checkpoint saving, then the desired behavior would be that an upload to the same path (with `overwrite=True`) either completely succeeds or fails (and previous content is kept). Since current blobfile is using blocks, this should be possible.

This behavior would agree with the python sdk behavior of `BlockBlobService.create_blob_from_path` I believe.

**Comment by christopher-hesse** [comment]
I think blobfile should be more atomic here.  I tried `create_blob_from_path` and it looks like it is atomic, but can result in invalid files:

```
import tempfile
import os
import sys
import time

from azure.storage.blob.blockblobservice import BlockBlobService

def main():
    svc = BlockBlobService(account_name="cshteststorage2", account_key=os.environ["AZURE_STORAGE_KEY"])
    with tempfile.TemporaryDirectory() as tmpdir:
        message = sys.argv[1].encode("utf8")
        local_path = os.path.join(tmpdir, "testblob")
        contents_size = 1024 * 1024 * 256
        assert len(message) == 1
        contents = message * contents_size
        with open(local_path, "wb") as f:
            f.write(contents)
        start = time.time()
        svc.create_blob_from_path("testcontainer2", "testblob", local_path)
        end = time.time()
        elapsed = end - start
        print("wrote",  elapsed, len(contents)/1e6/elapsed)

if __name__ == "__main__":
    main()
```

I launched two copies of this, one with `m` as the command line argument and the other with `o`, then killed the second copy.  This resulted in a file that was a combination of the two writes: `Counter({109: 205520896, 111: 62914560})`.  Concurrent writers like this doesn't seem to really be supported by azure storage, so what should probably happen is an error, rather than making a file with probably incorrect contents.

`blobfile`'s earlier usage of append blobs didn't work very well, but I've attempted to make the block blob version work a bit better.  I have made a small change in order to make the writing more atomic for blobfile: https://github.com/christopher-hesse/blobfile/commit/7991dbeca895b97fb2be420803eba8abb4b8bd2d

This is actually the previous behavior (although not in a published version).  The main downside is that if there are a bunch of failed writes to the same file, the number of uncommitted blocks could get too large and cause errors.  I have an idea for a possible workaround, but I'll have to try it out.

As a workaround, it seems like it should be fine to write to a temporary file, then copy it over the destination file, then delete the temporary file.  I don't do this in blobfile because there doesn't seem to be any way to clean up the temporary files automatically (like in the case of a crash) without changing bucket lifecycle rules.  It would be nice if that worked though.

**Comment by christopher-hesse** [comment]
I wrote a function that should clear the uncommitted blocks and run it whenever overwriting an existing file, to ensure that uncommitted blocks do not pile up and prevent a write from working: https://github.com/christopher-hesse/blobfile/commit/4b089868eafbe7dee86ca29010535165767ef00b

If the user was writing a file near the maximum size, and failed twice near the end of writing, they would likely have enough uncommitted blocks to hit the limit, which would cause a 409 error `RequestEntityTooLargeBlockCountExceedsLimit` and necessitate clearing the uncommitted blocks (which I believe would require restarting the upload).  The new method may be overkill, but could be removed later if that's the case.

Please try out the master version and see if it works as you expect, @hponde, and thanks for filing the issue!

**Comment by christopher-hesse** [comment]
Going to assume this works and close the issue.
