### ISSUE TITLE
benchmark range requests vs the current StreamingReadFile setup

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#117]
The current streaming read file setup does a single request, rather than 1 request per chunk, but this means it can't recycle connections and can cause GCE to throttle the connection rate (as noticed by @jacobhilton here: https://github.com/christopher-hesse/blobfile/issues/116).

The single request model seemed more efficient when reading large files, but it's possible that's not the case if buffer sizes are set high enough.  This should be tested as it looks like it would simplify a few things to just have the range requests instead.

**Comment by christopher-hesse** [comment]
Single streaming request: only does 1 GET request ideally, which reduces operation count, also the buffer size can be quite small since the operating system will buffer the packets of the response

1 request per chunk: this is much simpler, but seems to require a larger buffer size to make this work well, as well as having to do a larger number of requests

**Comment by christopher-hesse** [comment]
Added a debug flag, `USE_STREAMING_READ_REQUEST`, to try this out

**Comment by christopher-hesse** [comment]
It remains to be seen if this is a GCE issue or some issue with the test machine.

**Comment by christopher-hesse** [comment]
This was never investigated, so assuming it's a configuration issue on the user's side.
