### ISSUE TITLE
Output from harmless error

### ISSUE THREAD

**Issue by joschu** [christopher-hesse/blobfile#124]
I'm seeing a lot of outputs like
```
blobfile: error exception ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer')) while reading file at [...] attempt 0, sleeping for 0.1 seconds before retrying
```
I know I can use blobfile.configure ignore these. Would it make sense to ignore by default?

**Comment by christopher-hesse** [comment]
It might, I was worried that ignoring these would produce hangs that were not visible to the user.  The default behavior is to retry "transient" errors indefinitely, which would be confusing since your program could get stuck if the error was somehow not actually transient.

If I changed the default retry behavior to do a limited number of retries, then that wouldn't be an issue.  However if there was some slowdown due to retrying, that would not be as visible to the user.  So like if you were writing a bunch of files and the writes were failing 50% of the time, you might get bad throughput but not know it.

Are you getting a large number of these errors?  It's possible that there is something that should be fixed if you are.

If the errors are unavoidable, maybe something like the `RETRY_LOG_THRESHOLD` that currently exists here https://github.com/christopher-hesse/blobfile/blob/master/blobfile/ops.py#L78 but just for connection reset errors could be used.  That value is currently set to zero because it was masking errors when I was debugging things and was confusing.

**Comment by joschu** [comment]
Understood. I don't have a strong opinion on this -- maybe we should leave it as is, and I'll just make sure to configure it. I'm just seeing many pages of output in code that's downloading from many threads, on many MPI processes.

**Comment by christopher-hesse** [comment]
Just to check for future reference, are all the errors `ConnectionResetError`?  And is this a connection to azure blob storage from an azure machine?

**Comment by christopher-hesse** [comment]
I would prefer not to spam users with mostly useless messages, because then it's hard to see the important ones.

**Comment by joschu** [comment]
Sorry, forgot about this thread. Yeah, all the errors are ConnectionResetError. I think the reason I'm seeing all of them is because there are a jillion MPI processes. And maybe having all of these concurrent requests makes failures more likely.
I've resolved it with something like
```
if rank > 0:
        logging.basicConfig(level=logging.ERROR)
        bf.configure(log_callback=lambda message: None)
```

**Comment by christopher-hesse** [comment]
Thanks for the workaround.  I suspect that this is good enough for now in combination with `retry_log_threshold`.  I am open to making a special `retry_connectionreset_log_threshold` setting with some higher default value (like 3) should these errors be unavoidable.
