### ISSUE TITLE
Formatting of errors coming from azblob

### ISSUE THREAD

**Issue by nottombrown** [christopher-hesse/blobfile#126]
It seems like azure misformats the slashes into `%2F`. If they can't fix this, then perhaps blobfile could take responsibility for fixing the paths?

Example
```
blobfile.common.ConcurrentWriteFailure: message=Invalid block list, most likely a concurrent writer wrote to the same path: `https://<redacted>.blob.core.windows.net/<redacted>/tom%2Fsaves%2Flatest%2Fsomething.json`, request=<Request method=PUT 
```

**Comment by christopher-hesse** [comment]
I think `blobfile` does that, it should be easy to un-escape the url when printing the error (I believe the escaped url is required to be used with blob storage, otherwise if you had % or other not-url-safe characters in your filename, the server would be confused).

The fact that blobfile escapes `/` is because I use `urllib.parse.quote(path, safe="")` instead of the more default configuration of `urllib.parse.quote(path, safe="/")`.  I don't remember if that is necessary, but you should have a similar issue if you have, for instance, a space character in the path.

I'm not sure what azblob or azure has to do with this, is that just a guess on your part?
