### ISSUE TITLE
write timeouts may be handled poorly

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#135]
And don't seem to be configurable

**Comment by christopher-hesse** [comment]
Added configurable timeouts, the behavior is a bit confusing (presumably due to urllib3).

When uploading a large file to azure with a bad wifi connection, the first error happens after `READ_TIMEOUT` seconds, all subsequent errors take `CONNECT_TIMEOUT` seconds.

It seems like each chunk of `azure_write_chunk_size` has to be uploaded within the timeout period, or else the request will die.

The behavior I observed on windows is that `sock.sendall()` returns immediately, so it's possible that we could hit the read timeout as a result, since we will be waiting in `read` for the request to finish, which it will not do in time since we are uploading until we hit the timeout.

Users can at least set the timeouts to be higher to work around this, but maybe it would be better if we increased the timeout on slow connections.
