### ISSUE TITLE
streaming=True memory usage

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#167]
Should switch to use `chunk = memoryview(self._buf)[:size]` in `_common.py` and `chunk_mv = memoryview(chunk)` in `_azure.py`.

**Comment by christopherhesse** [comment]
Should also check if https://github.com/christopher-hesse/blobfile/pull/159 is faster with NPOT sized buffers (or lots of single bytes writes)

**Comment by christopher-hesse** [comment]
bytearray:

```
import time
from blobfile._common import BaseStreamingWriteFile

class TestFile(BaseStreamingWriteFile):
    def _upload_chunk(self, chunk: memoryview, finalize: bool) -> None:
        pass


def main():
    N = 2**17
    b = b"x" * 10

    f = TestFile(conf=None, chunk_size=8 * 2**20)
    start = time.time()
    for i in range(N):
        f.write(b)
    end = time.time()
    print(f"write elapsed {end - start}")


if __name__ == "__main__":
    main()
```

before:
```
python misc\blobfile_dev\write_speed.py                                                                                                                                                                                                                            
write elapsed 9.351279497146606
```

after:
```
python misc\blobfile_dev\write_speed.py 
write elapsed 0.059172868728637695
```

**Comment by christopher-hesse** [comment]
```
import resource
import blobfile as bf


def max_mem_usage() -> int:
    return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss * 1024

def main():
    bf.configure(azure_write_chunk_size=2**20)
    streaming = False
    print(f"streaming={streaming}")
    prev = max_mem_usage()
    contents = b"x" * (10 * 2 ** 20 + 1)
    cur = max_mem_usage()
    print(f"{cur - prev:,}")
    prev = cur
    with bf.BlobFile("az://cshteststorage2/testcontainer2/upload.bin", "wb", streaming=streaming) as f:
        f.write(contents)
    cur = max_mem_usage()
    print(f"{cur - prev:,}")


if __name__ == "__main__":
    main()
```

before:
```
 python misc/blobfile_dev/memory_usage.py
streaming=True
10,489,856
15,503,360
(blobfile) >  p python misc/blobfile_dev/memory_usage.py
streaming=False
10,489,856
5,038,080
```

after:

```
python misc/blobfile_dev/memory_usage.py
streaming=True
10,489,856
2,920,448
(blobfile) >  p python misc/blobfile_dev/memory_usage.py
streaming=False
10,489,856
5,050,368
```

**Comment by christopher-hesse** [comment]
@hauntsaninja I ended up using more memoryviews + bytearray when not doing a single large `f.write()`, does this look good to you?   https://github.com/christopher-hesse/blobfile/compare/1.2.0...master

**Comment by hauntsaninja** [comment]
It does look good to me! Thanks for making these improvements.

One note is that you can annotate an argument as `bytes` and type checkers will accept passing `memoryview` / `bytearray` automatically (similar to how type checkers allow you to pass an int to a float, even though ints are not floats). I mention this because it can help guard against the one sometimes bug causing thing about memoryviews: that they can allow you to mutate the original object.

(Also I guess you could do `chunk = memoryview(buf)[:size]` on L553 and `self._buf = bytearray(memoryview(b)[size:])`) on L580 if you wanted to be explicit about which copies we're eliding / make _upload_buf really not care whether the input is exactly a memoryview or not)

**Comment by christopher-hesse** [comment]
It looks like my super old version of pyright doesn't accept that, and upgrading it would be a pain :(
