### ISSUE TITLE
_StreamingReadFile should handle fork()

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#72]
It seems likely that `_StreamingReadFile` can keep a connection open across a fork.  Should consider discarding the connection during a pid change, or else not keeping a persistent connection

**Comment by christopherhesse** [comment]
https://github.com/urllib3/urllib3/issues/850

**Comment by christopher-hesse** [comment]
Calling `fork()` with an open socket seems to work, so unclear if this is actually an issue in practice.

**Comment by christopher-hesse** [comment]
```
import os
import blobfile as bf
import time

path = "gs://bucket/100mb.bin"
f = bf.BlobFile(path, "rb")
f.read(1)
fork_result = os.fork()
print(f"{os.getpid()} fork {fork_result}")
if fork_result != 0:
    print(f"{os.getpid()} sleep")
    time.sleep(30)
print(f"{os.getpid()} {len(f.read())}")
print(f"{os.getpid()} exited")
f.close()
```

**Comment by christopher-hesse** [comment]
Right now we use the connection as a file-like object so that we can call readinto()

Instead, we could set the default buffer size to a much larger value and then do a request each time readinto() is called (which is likely to reuse connections from the connection pool).  This would avoid:

* using preload_content=False
* returning connections to the connection pool
* the duplicate retry loop in readinto

However, it could impact read performance, so we should benchmark performance on a desktop machine and GCE instance.

**Comment by christopher-hesse** [comment]
It looks like some amount is small amount is buffered, here's with a debug print on `_get_file` and `RETRY_LOG_THRESHOLD=0`:

```
get_file 0
51 fork 53
51 sleep
53 fork 0
53 99999999
53 exited
51 done sleeping
blobfile: error HTTPSConnectionPool(host='storage.googleapis.com', port=443): Read timed out. when executing readinto(1048576) at offset 8192 on file gs://csh-test-3/100mb.bin, sleeping for 0.2 seconds before retrying
get_file 8192
51 99999999
51 exited
```
